### ISSUE TITLE
Wrong command given to run the demo app

### ISSUE THREAD

**Issue by DeezleSince74** [GetStream/react-native-example#1]
The instructions for the final step to run the app should be **npm start**, not npm run.

**Comment by gianpaj** [comment]
that's an easy PR to do 🙂 maybe even a quick way of getting #hacktoberfest t-shirt 😄

**Comment by gyleodhis** [comment]
npm start returns the following output:
10:20:03: Unable to start server
  See https://git.io/v5vcn for more information, either install watchman or run the following snippet:
    sudo sysctl -w fs.inotify.max_user_instances=1024
    sudo sysctl -w fs.inotify.max_user_watches=12288
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-activity-feed-showcase@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native-activity-feed-showcase@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gyleodhis/.npm/_logs/2019-05-31T07_20_03_783Z-debug.log

**Comment by tbarbugli** [comment]
@gyleodhis did you try following the instructions from the error message?

**Comment by vishalnarkhede** [comment]
Please check the updated instructions - https://github.com/GetStream/react-native-example#1-install-dependencies
