### ISSUE TITLE
app is not working

### ISSUE THREAD

**Issue by Wings1986** [GetStream/react-native-example#19]
![IMG_0019](https://user-images.githubusercontent.com/9060374/70735061-0491d500-1d40-11ea-9672-0dfd445df8e1.PNG)

I got errors when app launch.
Please check screenshot  and let me know

**Comment by tbarbugli** [comment]
did you update the .env file and include your API credentials?

**Comment by Wings1986** [comment]
EDIT: removed the images since they included API secrets

Note: the API secret is used as the user token (hence the error)

**Comment by tbarbugli** [comment]
@jaapbakker88 can you point @Wings1986 in the right direction on the example app setup and make sure we explain this clearly in the readme as well? ideally we have an env variable to use dev tokens so that there is less work needed to get started

**Comment by Wings1986** [comment]
Hello,
I followed your readme and build project(env file included API secrets and id, token)
But I can get over errors and can not fix them myself.
Please let me know what i should do?

**Comment by jaapbakker88** [comment]
I added more detailed instructions for how to get setup with this repo. I also added one dependency which made it crash.

Can you let me know the exact steps you took to get this up and running. I'll see where it goes wrong and update accordingly.

**Comment by vishalnarkhede** [comment]
@Wings1986 Here are new instructions to run the app - https://github.com/GetStream/react-native-example#1-install-dependencies
