### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by bunyaminmrcn** [GetStream/react-native-example#24]
Hi , i am cloned the repo and configured with latest dependencies. Also ran 
`npm run init-data` command to init app . App looks fine but clicking the post on HomeScreen , i got this error . 
  While debugging the app `feedGroup, userId` return undefined in `SinglePostScreen.js`
The link is my `package.json` with latest dependencies.

https://gist.github.com/bunyaminmrcn/e58bc19154fea4e3affd450528bcd30f

Cannot read property 'id' of undefined
- node_modules\react-native-activity-feed-core\lib\Context\Feed.js:118:13 in getActivityPath

![error_activity](https://user-images.githubusercontent.com/30148504/71752128-fd696d00-2e8e-11ea-8f9a-808e7ee22162.png)

And it is warning but red in the console , didn't understand why is red like error

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: %s.%s%s, undefined,  You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at SinglePostScreen.js:77.,
    in Activity (at utils.js:37)
    in ImmutableItemWrapper (at FlatFeed.js:132)
    in RCTView (at VirtualizedList.js:1925)
    in CellRenderer (at VirtualizedList.js:767)
    in RCTView (at ScrollView.js:1038)
    in RCTScrollView (at ScrollView.js:1166)
    in AndroidSwipeRefreshLayout (at RefreshControl.js:186)
    in RefreshControl (at VirtualizedList.js:1170)
    in ScrollView (at VirtualizedList.js:1166)
    in VirtualizedList (at FlatList.js:676)
    in FlatList (at FlatFeed.js:175)
    in FlatFeedInner (at FlatFeed.js:105)
    in FeedInner (at Feed.js:1451)
    in StreamAppConsumer (at Feed.js:1455)
    in Feed (at FlatFeed.js:92)
    in FlatFeed (at SinglePost.js:55)
    in SinglePost (at SinglePostScreen.js:49)
    in RCTView (at SafeAreaView.js:40)
    in SafeAreaView (at SinglePostScreen.js:48)
    in SinglePostScreen (at SceneView.js:9)
    in SceneView (at StackView.tsx:271)
    in RCTView (at CardContainer.tsx:162)
    in RCTView (at CardContainer.tsx:161)
    in RCTView (at PointerEventsView.tsx:35)
    in PointerEventsView (at Card.tsx:445)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Card.tsx:432)
    in PanGestureHandler (at Card.tsx:425)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Card.tsx:421)
    in RCTView (at Card.tsx:414)
    in Card (at CardContainer.tsx:128)
    in CardContainer (at CardStack.tsx:496)
    in RCTView (at CardStack.tsx:110)
    in MaybeScreen (at CardStack.tsx:489)
    in RCTView (at CardStack.tsx:93)
    in MaybeScreenContainer (at CardStack.tsx:399)
    in CardStack (at StackView.tsx:386)
    in KeyboardManager (at StackView.tsx:384)
    in RNCSafeAreaView (at src/index.tsx:26)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:22)
    in SafeAreaProviderCompat (at StackView.tsx:381)
    in StackView (at StackView.tsx:41)
    in StackView (at createStackNavigator.tsx:33)
    in Unknown (at createNavigator.js:80)
    in Navigator (at createAppContainer.js:430)
    in NavigationContainer (at Main.js:137)
    in StreamApp (at Main.js:123)
    in App (at App.js:11)
    in App
    in RootErrorBoundary (at withExpoRoot.js:25)
    in ExpoRoot (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)`

**Comment by shodgetts** [comment]
Hi bunyaminmrcn. Sorry you're having issues. The developer team is out for the weekend, but they'll be in touch as soon as they're back.

**Comment by bunyaminmrcn** [comment]
So quick  No problem bro 😎

**Comment by shodgetts** [comment]
bunyaminmrcn, I was able to clone and start up the repo without issue. Can you just make sure that

1. You've completed the tutorial (https://getstream.io/react-native-activity-feed/tutorial/)
2. You're creating a .env file with API_SECRET, API_KEY, APP_ID, adding in the details from the tutorial app
3. Running the npm run init-data command

**Comment by bunyaminmrcn** [comment]
I did

**Comment by jaapbakker88** [comment]
@bunyaminmrcn I pushed a fix for the single post screen, can you pull and confirm it works?

**Comment by bunyaminmrcn** [comment]
Yes, it fixed.
