### ISSUE TITLE
Running "npm run init-data 

### ISSUE THREAD

**Issue by jamesrenaudcode** [GetStream/react-native-example#25]
This doesn't return anything for me and I have my keys in the .env file. The message I get is "STREAM_API_KEY" not defined in any .env files. Any suggestions?

**Comment by luisfuertes** [comment]
If i do `npm run init-data` get this error:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/create-data - Not found
npm ERR! 404 
npm ERR! 404  'create-data@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url
```

**Comment by vishalnarkhede** [comment]
@jamesrenaudcode we have updated the example app now. Please follow latest instructions - https://github.com/GetStream/react-native-example#3-get-your-usertoken-and-setup-demo-data

Please re-open if you still face the issue :)
