### ISSUE TITLE
Android Emulator white screen

### ISSUE THREAD

**Issue by ronglianglei** [GetStream/react-native-example#33]
I followed Setup instructions. Then, I started the app from console, it displayed following, seems no error to me. However, from android emulator, it showed white screen  after loaded. I waited for long time, and I tried  couple times, only white screen is displayed in emulator. 

 › Press a to open Android device or emulator.
 › Press s to send the app URL to your phone number or email address
 › Press q to display QR code.
 › Press r to restart packager, or R to restart packager and clear cache.
 › Press d to toggle development mode. (current mode: development)

6:50:41 PM: ::xxxx:192.168.0.18 - - [04/Sep/2020:22:50:41 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.12.1"
6:50:51 PM: ::xxxx:192.168.0.18 - - [04/Sep/2020:22:50:51 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.12.1"
6:51:01 PM: ::xxxx:192.168.0.18 - - [04/Sep/2020:22:51:01 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.12.1"

**Comment by vishalnarkhede** [comment]
We have updated the example app. Please re-open if you still face the issue!!
