### ISSUE TITLE
Npm install is not working 

### ISSUE THREAD

**Issue by yogeshthanvi** [GetStream/react-native-example#4]
I am getting below error 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ansi-styles@2.2.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'ReactNativeSampleApp'
npm ERR! notarget

**Comment by cbedoy** [comment]
Same error

```
➜  react-native-example git:(master) ✗ npm run init-data

> react-native-activity-feed-showcase@0.1.0 init-data ...ReactNativeBridge/react-native-example
> babel-node scripts/initData.js

sh: babel-node: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-native-activity-feed-showcase@0.1.0 init-data: `babel-node scripts/initData.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-native-activity-feed-showcase@0.1.0 init-data script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bedoy/.npm/_logs/2019-08-09T01_18_05_356Z-debug.log```

**Comment by vishalnarkhede** [comment]
Hey @cbedoy , the error that you reported has been fixed now - https://github.com/GetStream/react-native-example/issues/10

@yogeshthanvi are you still facing the issue?
