### ISSUE TITLE
Invalid Signature

### ISSUE THREAD

**Issue by thagar** [GetStream/react-native-example#5]
When I launch the app I get an error that says invalid signature.. how do I fix that ?

**Comment by vishalnarkhede** [comment]
@thagar can you please post the full error that you got?

**Comment by Nturibi** [comment]
<img width="1039" alt="Screen Shot 2019-12-23 at 9 59 19 AM" src="https://user-images.githubusercontent.com/23113353/71341460-fd05d380-256a-11ea-96bf-d263226c7994.png">
Assuming this was the error @thagar  had. what might be the issue

**Comment by Nturibi** [comment]
More context: Seems like all users get same JWT signature. Is this expected?
<img width="873" alt="Screen Shot 2019-12-24 at 7 01 30 AM" src="https://user-images.githubusercontent.com/23113353/71393051-a6a49d80-261b-11ea-9ab6-1b07a8fed233.png">

**Comment by vishalnarkhede** [comment]
@Nturibi are you still facing the issue. We update the example recently - https://github.com/GetStream/react-native-example#1-install-dependencies

Please reopen if you are still facing the issue :)
