### ISSUE TITLE
Running "npm run init-data" causes error

### ISSUE THREAD

**Issue by shima20** [GetStream/react-native-example#7]
`react-native-example-master/scripts/initData.js: Unexpected token (6:12)

> 6 | import type { UserSession, CloudClient } from '../types';
    |             ^`

**Comment by tconlin** [comment]
+1

**Comment by SamuelY** [comment]
+1 Does anyone has solution about this?

**Comment by BrunoSette** [comment]
**The error here:** 


```
> react-native-activity-feed-showcase@0.1.0 init-data /Users/bruno/react-native-example
> babel-node scripts/initData.js

sh: babel-node: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-native-activity-feed-showcase@0.1.0 init-data: `babel-node scripts/initData.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-native-activity-feed-showcase@0.1.0 init-data script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bruno/.npm/_logs/2019-07-19T14_19_54_908Z-debug.log
```

**Comment by walter-grace** [comment]
> **The error here:**
> 
> ```
> > react-native-activity-feed-showcase@0.1.0 init-data /Users/bruno/react-native-example
> > babel-node scripts/initData.js
> 
> sh: babel-node: command not found
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! react-native-activity-feed-showcase@0.1.0 init-data: `babel-node scripts/initData.js`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the react-native-activity-feed-showcase@0.1.0 init-data script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/bruno/.npm/_logs/2019-07-19T14_19_54_908Z-debug.log
> ```

Running into the same issues here;

**Comment by CreativExit** [comment]
Install npm install -g babel-cli fix your problem

**Comment by aldrinc** [comment]
@shima20 @SamuelY @tconlin Workaround for flow error here https://github.com/GetStream/react-native-example/issues/10

**Comment by rafaelcavalcante** [comment]
The @CreativExit code solves one of the problems. After installing babel-cli i got the same error that @shima20 reported. Thankfully @aldrinc reply solved the whole problem :)

**Comment by vishalnarkhede** [comment]
Thanks alot @aldrinc @CreativExit for the solution. I have added the same fix in code itself now - https://github.com/GetStream/react-native-example/commit/38d6064a1b250b63980f7b240991bebd53f1cdb2

Closing this issue now!
