### ISSUE TITLE
There are a lot of errors in this code..please kindly review them

### ISSUE THREAD

**Issue by Simisoluwa** [GetStream/react-native-example#8]

**Comment by tbarbugli** [comment]
a bit of context would help ;)

**Comment by rafaelcavalcante** [comment]
- "ListView is deprecated and will be removed in a future release. See https://fb.me/nolistview for more information"
- There is some erros solved by the community in the other _open_ issues
- The example application does not reproduce the screenshots in the readme file

**Comment by rafaelcavalcante** [comment]
I was wondering... i ran this app and the posts from people i follow are shown in my profile (and not in the "home" page). Is this how it's supposed to be?

**Comment by vishalnarkhede** [comment]
We have updated the example recently.
